name: Update Random Quote in README

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Random Quote from ZenQuotes API
        run: |
          RESPONSE=$(curl -s "https://zenquotes.io/api/random")
          QUOTE=$(echo $RESPONSE | jq -r '.[0].q')
          AUTHOR=$(echo $RESPONSE | jq -r '.[0].a')
          ESCAPED_QUOTE=$(echo "$QUOTE" | sed 's/"/\\"/g')
          ESCAPED_AUTHOR=$(echo "$AUTHOR" | sed 's/"/\\"/g')
          echo "QUOTE=$ESCAPED_QUOTE" >> $GITHUB_ENV
          echo "AUTHOR=$ESCAPED_AUTHOR" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/## ✨ Random Quote/,$d' README.md
          echo '## ✨ Random Quote' >> README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '' >> README.md
          echo '  <blockquote style="background-color:#1e1e1e; color:#f8f8f2; padding:15px; border-radius:10px; font-size:16px; width:80%; margin:auto; box-shadow: 2px 2px 10px rgba(0,0,0,0.2);">' >> README.md
          echo '    💡 <strong>"'"$QUOTE"'"</strong>' >> README.md
          echo '    <br>' >> README.md
          echo '    <sub>— ✍️ <strong>'"$AUTHOR"'</strong></sub>' >> README.md
          echo '  </blockquote>' >> README.md
          echo '' >> README.md
          echo '</div>' >> README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated random quote" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
