name: Update Random Quote in README

on:
  schedule:
    - cron: '*/40 * * * *'  # Runs every 40 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Random Quote
        run: |
          QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content')
          AUTHOR=$(curl -s https://api.quotable.io/random | jq -r '.author')
          ESCAPED_QUOTE=$(echo "$QUOTE" | sed 's/ /+/g' | sed 's/"/%22/g')
          echo "QUOTE=$ESCAPED_QUOTE" >> $GITHUB_ENV
          echo "AUTHOR=$AUTHOR" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i '/https:\/\/readme-typing-svg.herokuapp.com/c\  <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&pause=1000&color=F7B93E&width=600&lines=%22'"$QUOTE"' %22+-+'"$AUTHOR"'" alt="Random Quote">' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated random quote" || echo "No changes to commit"
          git push
