name: Update Random Quote in README
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install jq (if missing)
        run: sudo apt-get install -y jq

      - name: Fetch Random Quote (Using Zen Quotes API)
        run: |
          curl -s https://zenquotes.io/api/random | jq -r '"## ✨ Random Quote\n\n> \"" + .[0].q + "\"\n\n— " + .[0].a' > QUOTE.md
      
      - name: Update README
        run: |
          sed -i '/## ✨ Random Quote/,$d' README.md
          cat QUOTE.md >> README.md
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated random quote" || echo "No changes to commit"
          git push
